model:
  image_size: [224, 224]
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  
data:
  train_split: 0.8
  validation_split: 0.2
  augmentation:
    horizontal_flip: true
    rotation_range: 15
    zoom_range: 0.1
    brightness_range: [0.8, 1.2]

paths:
  raw_data: 'data/raw'
  processed_data: 'data/processed'
  models: 'models/saved_models'
  history: 'models/model_history'